// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v5.26.1
// source: github.com/dogmatiq/veracity/internal/integration/internal/integrationjournal/record.proto

package integrationjournal

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
)

// TryGetCommandEnqueued returns x.Operation.CommandEnqueued if x.Operation is a [Record_CommandEnqueued].
// Otherwise, ok is false and v is the zero-value.
func (x *Record) TryGetCommandEnqueued() (v *CommandEnqueued, ok bool) {
	if x, ok := x.GetOperation().(*Record_CommandEnqueued); ok {
		return x.CommandEnqueued, true
	}
	return v, false
}

// TryGetCommandHandled returns x.Operation.CommandHandled if x.Operation is a [Record_CommandHandled].
// Otherwise, ok is false and v is the zero-value.
func (x *Record) TryGetCommandHandled() (v *CommandHandled, ok bool) {
	if x, ok := x.GetOperation().(*Record_CommandHandled); ok {
		return x.CommandHandled, true
	}
	return v, false
}

// TryGetEventsAppendedToStream returns x.Operation.EventsAppendedToStream if x.Operation is a [Record_EventsAppendedToStream].
// Otherwise, ok is false and v is the zero-value.
func (x *Record) TryGetEventsAppendedToStream() (v *EventsAppendedToStream, ok bool) {
	if x, ok := x.GetOperation().(*Record_EventsAppendedToStream); ok {
		return x.EventsAppendedToStream, true
	}
	return v, false
}

type RecordBuilder struct {
	prototype Record
}

// NewRecordBuilder returns a builder that constructs [Record] messages.
func NewRecordBuilder() *RecordBuilder {
	return &RecordBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *RecordBuilder) From(x *Record) *RecordBuilder {
	b.prototype.Operation = x.Operation
	return b
}

// Build returns a new [Record] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *RecordBuilder) Build() *Record {
	return &Record{
		Operation: b.prototype.Operation,
	}
}

// WithCommandEnqueued configures the builder to set the Operation field to a
// [Record_CommandEnqueued] value containing v, then returns b
func (b *RecordBuilder) WithCommandEnqueued(v *CommandEnqueued) *RecordBuilder {
	b.prototype.Operation = &Record_CommandEnqueued{CommandEnqueued: v}
	return b
}

// WithCommandHandled configures the builder to set the Operation field to a
// [Record_CommandHandled] value containing v, then returns b
func (b *RecordBuilder) WithCommandHandled(v *CommandHandled) *RecordBuilder {
	b.prototype.Operation = &Record_CommandHandled{CommandHandled: v}
	return b
}

// WithEventsAppendedToStream configures the builder to set the Operation field to a
// [Record_EventsAppendedToStream] value containing v, then returns b
func (b *RecordBuilder) WithEventsAppendedToStream(v *EventsAppendedToStream) *RecordBuilder {
	b.prototype.Operation = &Record_EventsAppendedToStream{EventsAppendedToStream: v}
	return b
}

type CommandEnqueuedBuilder struct {
	prototype CommandEnqueued
}

// NewCommandEnqueuedBuilder returns a builder that constructs [CommandEnqueued] messages.
func NewCommandEnqueuedBuilder() *CommandEnqueuedBuilder {
	return &CommandEnqueuedBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *CommandEnqueuedBuilder) From(x *CommandEnqueued) *CommandEnqueuedBuilder {
	b.prototype.Command = x.Command
	return b
}

// Build returns a new [CommandEnqueued] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *CommandEnqueuedBuilder) Build() *CommandEnqueued {
	return &CommandEnqueued{
		Command: b.prototype.Command,
	}
}

// WithCommand configures the builder to set the Command field to v,
// then returns b.
func (b *CommandEnqueuedBuilder) WithCommand(v *envelopepb.Envelope) *CommandEnqueuedBuilder {
	b.prototype.Command = v
	return b
}

type CommandHandledBuilder struct {
	prototype CommandHandled
}

// NewCommandHandledBuilder returns a builder that constructs [CommandHandled] messages.
func NewCommandHandledBuilder() *CommandHandledBuilder {
	return &CommandHandledBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *CommandHandledBuilder) From(x *CommandHandled) *CommandHandledBuilder {
	b.prototype.CommandId = x.CommandId
	b.prototype.Events = x.Events
	b.prototype.EventStreamId = x.EventStreamId
	b.prototype.LowestPossibleEventOffset = x.LowestPossibleEventOffset
	return b
}

// Build returns a new [CommandHandled] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *CommandHandledBuilder) Build() *CommandHandled {
	return &CommandHandled{
		CommandId:                 b.prototype.CommandId,
		Events:                    b.prototype.Events,
		EventStreamId:             b.prototype.EventStreamId,
		LowestPossibleEventOffset: b.prototype.LowestPossibleEventOffset,
	}
}

// WithCommandId configures the builder to set the CommandId field to v,
// then returns b.
func (b *CommandHandledBuilder) WithCommandId(v *uuidpb.UUID) *CommandHandledBuilder {
	b.prototype.CommandId = v
	return b
}

// WithEvents configures the builder to set the Events field to v,
// then returns b.
func (b *CommandHandledBuilder) WithEvents(v []*envelopepb.Envelope) *CommandHandledBuilder {
	b.prototype.Events = v
	return b
}

// WithEventStreamId configures the builder to set the EventStreamId field to v,
// then returns b.
func (b *CommandHandledBuilder) WithEventStreamId(v *uuidpb.UUID) *CommandHandledBuilder {
	b.prototype.EventStreamId = v
	return b
}

// WithLowestPossibleEventOffset configures the builder to set the LowestPossibleEventOffset field to v,
// then returns b.
func (b *CommandHandledBuilder) WithLowestPossibleEventOffset(v uint64) *CommandHandledBuilder {
	b.prototype.LowestPossibleEventOffset = v
	return b
}

type EventsAppendedToStreamBuilder struct {
	prototype EventsAppendedToStream
}

// NewEventsAppendedToStreamBuilder returns a builder that constructs [EventsAppendedToStream] messages.
func NewEventsAppendedToStreamBuilder() *EventsAppendedToStreamBuilder {
	return &EventsAppendedToStreamBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *EventsAppendedToStreamBuilder) From(x *EventsAppendedToStream) *EventsAppendedToStreamBuilder {
	b.prototype.CommandId = x.CommandId
	b.prototype.EventStreamId = x.EventStreamId
	b.prototype.EventOffset = x.EventOffset
	return b
}

// Build returns a new [EventsAppendedToStream] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *EventsAppendedToStreamBuilder) Build() *EventsAppendedToStream {
	return &EventsAppendedToStream{
		CommandId:     b.prototype.CommandId,
		EventStreamId: b.prototype.EventStreamId,
		EventOffset:   b.prototype.EventOffset,
	}
}

// WithCommandId configures the builder to set the CommandId field to v,
// then returns b.
func (b *EventsAppendedToStreamBuilder) WithCommandId(v *uuidpb.UUID) *EventsAppendedToStreamBuilder {
	b.prototype.CommandId = v
	return b
}

// WithEventStreamId configures the builder to set the EventStreamId field to v,
// then returns b.
func (b *EventsAppendedToStreamBuilder) WithEventStreamId(v *uuidpb.UUID) *EventsAppendedToStreamBuilder {
	b.prototype.EventStreamId = v
	return b
}

// WithEventOffset configures the builder to set the EventOffset field to v,
// then returns b.
func (b *EventsAppendedToStreamBuilder) WithEventOffset(v uint64) *EventsAppendedToStreamBuilder {
	b.prototype.EventOffset = v
	return b
}

// MustSwitch_Record_Operation invokes one of the given functions based on
// the value of x.Operation.
//
// It panics if x.Operation is nil.
func MustSwitch_Record_Operation(
	x *Record,
	caseCommandEnqueued func(*CommandEnqueued),
	caseCommandHandled func(*CommandHandled),
	caseEventsAppendedToStream func(*EventsAppendedToStream),
) {
	switch v := x.GetOperation().(type) {
	case *Record_CommandEnqueued:
		caseCommandEnqueued(v.CommandEnqueued)
	case *Record_CommandHandled:
		caseCommandHandled(v.CommandHandled)
	case *Record_EventsAppendedToStream:
		caseEventsAppendedToStream(v.EventsAppendedToStream)
	default:
		panic("MustSwitch_Record_Operation: x.Operation is nil")
	}
}

// Switch_Record_Operation invokes one of the given functions based on
// the value of x.Operation.
//
// It calls none() if x.Operation is nil.
func Switch_Record_Operation(
	x *Record,
	caseCommandEnqueued func(*CommandEnqueued),
	caseCommandHandled func(*CommandHandled),
	caseEventsAppendedToStream func(*EventsAppendedToStream),
	none func(),
) {
	switch v := x.GetOperation().(type) {
	case *Record_CommandEnqueued:
		caseCommandEnqueued(v.CommandEnqueued)
	case *Record_CommandHandled:
		caseCommandHandled(v.CommandHandled)
	case *Record_EventsAppendedToStream:
		caseEventsAppendedToStream(v.EventsAppendedToStream)
	default:
		none()
	}
}

// MustMap_Record_Operation maps x.Operation to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Operation,
// and returns that function's result. It panics if x.Operation is nil.
func MustMap_Record_Operation[T any](
	x *Record,
	caseCommandEnqueued func(*CommandEnqueued) T,
	caseCommandHandled func(*CommandHandled) T,
	caseEventsAppendedToStream func(*EventsAppendedToStream) T,
) T {
	switch v := x.GetOperation().(type) {
	case *Record_CommandEnqueued:
		return caseCommandEnqueued(v.CommandEnqueued)
	case *Record_CommandHandled:
		return caseCommandHandled(v.CommandHandled)
	case *Record_EventsAppendedToStream:
		return caseEventsAppendedToStream(v.EventsAppendedToStream)
	default:
		panic("MustMap_Record_Operation: x.Operation is nil")
	}
}

// Map_Record_Operation maps x.Operation to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Operation,
// and returns that function's result. It calls none() if x.Operation is nil.
func Map_Record_Operation[T any](
	x *Record,
	caseCommandEnqueued func(*CommandEnqueued) T,
	caseCommandHandled func(*CommandHandled) T,
	caseEventsAppendedToStream func(*EventsAppendedToStream) T,
	none func() T,
) T {
	switch v := x.GetOperation().(type) {
	case *Record_CommandEnqueued:
		return caseCommandEnqueued(v.CommandEnqueued)
	case *Record_CommandHandled:
		return caseCommandHandled(v.CommandHandled)
	case *Record_EventsAppendedToStream:
		return caseEventsAppendedToStream(v.EventsAppendedToStream)
	default:
		return none()
	}
}

// SetCommandEnqueued sets the x.Operation field to a [Record_CommandEnqueued] value containing v,
// then returns x.
func (x *Record) SetCommandEnqueued(v *CommandEnqueued) {
	x.Operation = &Record_CommandEnqueued{CommandEnqueued: v}
}

// SetCommandHandled sets the x.Operation field to a [Record_CommandHandled] value containing v,
// then returns x.
func (x *Record) SetCommandHandled(v *CommandHandled) {
	x.Operation = &Record_CommandHandled{CommandHandled: v}
}

// SetEventsAppendedToStream sets the x.Operation field to a [Record_EventsAppendedToStream] value containing v,
// then returns x.
func (x *Record) SetEventsAppendedToStream(v *EventsAppendedToStream) {
	x.Operation = &Record_EventsAppendedToStream{EventsAppendedToStream: v}
}

// SetCommand sets the x.Command field to v, then returns x.
func (x *CommandEnqueued) SetCommand(v *envelopepb.Envelope) {
	x.Command = v
}

// SetCommandId sets the x.CommandId field to v, then returns x.
func (x *CommandHandled) SetCommandId(v *uuidpb.UUID) {
	x.CommandId = v
}

// SetEvents sets the x.Events field to v, then returns x.
func (x *CommandHandled) SetEvents(v []*envelopepb.Envelope) {
	x.Events = v
}

// SetEventStreamId sets the x.EventStreamId field to v, then returns x.
func (x *CommandHandled) SetEventStreamId(v *uuidpb.UUID) {
	x.EventStreamId = v
}

// SetLowestPossibleEventOffset sets the x.LowestPossibleEventOffset field to v, then returns x.
func (x *CommandHandled) SetLowestPossibleEventOffset(v uint64) {
	x.LowestPossibleEventOffset = v
}

// SetCommandId sets the x.CommandId field to v, then returns x.
func (x *EventsAppendedToStream) SetCommandId(v *uuidpb.UUID) {
	x.CommandId = v
}

// SetEventStreamId sets the x.EventStreamId field to v, then returns x.
func (x *EventsAppendedToStream) SetEventStreamId(v *uuidpb.UUID) {
	x.EventStreamId = v
}

// SetEventOffset sets the x.EventOffset field to v, then returns x.
func (x *EventsAppendedToStream) SetEventOffset(v uint64) {
	x.EventOffset = v
}
