// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v4.24.2
// source: github.com/dogmatiq/veracity/internal/cluster/internal/registrypb/registration.proto

package registrypb
