// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/dogmatiq/veracity/internal/cluster/internal/registrypb/registration.proto

package registrypb

import (
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is a unique identifier for the node.
	Id *uuidpb.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Addresses is a list of network addresses at which the node's gRPC API can
	// be contacted.
	Addresses     []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() *uuidpb.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Registration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node is the node that is registered.
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// ExpiresAt is the time at which the registration expires if not renewed.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescGZIP(), []int{1}
}

func (x *Registration) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Registration) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDesc = "" +
	"\n" +
	"Tgithub.com/dogmatiq/veracity/internal/cluster/internal/registrypb/registration.proto\x12\x1cveracity.cluster.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"J\n" +
	"\x04Node\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\x02id\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"\x81\x01\n" +
	"\fRegistration\x126\n" +
	"\x04node\x18\x01 \x01(\v2\".veracity.cluster.registry.v1.NodeR\x04node\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtBCZAgithub.com/dogmatiq/veracity/internal/cluster/internal/registrypbb\x06proto3"

var (
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescData []byte
)

func file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDesc), len(file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDescData
}

var file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_goTypes = []any{
	(*Node)(nil),                  // 0: veracity.cluster.registry.v1.Node
	(*Registration)(nil),          // 1: veracity.cluster.registry.v1.Registration
	(*uuidpb.UUID)(nil),           // 2: dogma.protobuf.UUID
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_depIdxs = []int32{
	2, // 0: veracity.cluster.registry.v1.Node.id:type_name -> dogma.protobuf.UUID
	0, // 1: veracity.cluster.registry.v1.Registration.node:type_name -> veracity.cluster.registry.v1.Node
	3, // 2: veracity.cluster.registry.v1.Registration.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_init()
}
func file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_init() {
	if File_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDesc), len(file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto = out.File
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_goTypes = nil
	file_github_com_dogmatiq_veracity_internal_cluster_internal_registrypb_registration_proto_depIdxs = nil
}
