// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: github.com/dogmatiq/veracity/internal/queue/journal.proto

package queue

import (
	envelopespec "github.com/dogmatiq/interopspec/envelopespec"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JournalRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOf:
	//
	//	*JournalRecord_Enqueue
	//	*JournalRecord_Acquire
	//	*JournalRecord_Ack
	//	*JournalRecord_Reject
	OneOf isJournalRecord_OneOf `protobuf_oneof:"OneOf"`
}

func (x *JournalRecord) Reset() {
	*x = JournalRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalRecord) ProtoMessage() {}

func (x *JournalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalRecord.ProtoReflect.Descriptor instead.
func (*JournalRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{0}
}

func (m *JournalRecord) GetOneOf() isJournalRecord_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (x *JournalRecord) GetEnqueue() *EnqueueRecord {
	if x, ok := x.GetOneOf().(*JournalRecord_Enqueue); ok {
		return x.Enqueue
	}
	return nil
}

func (x *JournalRecord) GetAcquire() *AcquireRecord {
	if x, ok := x.GetOneOf().(*JournalRecord_Acquire); ok {
		return x.Acquire
	}
	return nil
}

func (x *JournalRecord) GetAck() *AckRecord {
	if x, ok := x.GetOneOf().(*JournalRecord_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *JournalRecord) GetReject() *RejectRecord {
	if x, ok := x.GetOneOf().(*JournalRecord_Reject); ok {
		return x.Reject
	}
	return nil
}

type isJournalRecord_OneOf interface {
	isJournalRecord_OneOf()
}

type JournalRecord_Enqueue struct {
	Enqueue *EnqueueRecord `protobuf:"bytes,1,opt,name=enqueue,proto3,oneof"`
}

type JournalRecord_Acquire struct {
	Acquire *AcquireRecord `protobuf:"bytes,2,opt,name=acquire,proto3,oneof"`
}

type JournalRecord_Ack struct {
	Ack *AckRecord `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type JournalRecord_Reject struct {
	Reject *RejectRecord `protobuf:"bytes,4,opt,name=reject,proto3,oneof"`
}

func (*JournalRecord_Enqueue) isJournalRecord_OneOf() {}

func (*JournalRecord_Acquire) isJournalRecord_OneOf() {}

func (*JournalRecord_Ack) isJournalRecord_OneOf() {}

func (*JournalRecord_Reject) isJournalRecord_OneOf() {}

type JournalMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envelope *envelopespec.Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Key      string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Priority int64                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MetaData *anypb.Any             `protobuf:"bytes,4,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
}

func (x *JournalMessage) Reset() {
	*x = JournalMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalMessage) ProtoMessage() {}

func (x *JournalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalMessage.ProtoReflect.Descriptor instead.
func (*JournalMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{1}
}

func (x *JournalMessage) GetEnvelope() *envelopespec.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *JournalMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *JournalMessage) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JournalMessage) GetMetaData() *anypb.Any {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type EnqueueRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*JournalMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *EnqueueRecord) Reset() {
	*x = EnqueueRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRecord) ProtoMessage() {}

func (x *EnqueueRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRecord.ProtoReflect.Descriptor instead.
func (*EnqueueRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueRecord) GetMessages() []*JournalMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AcquireRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AcquireRecord) Reset() {
	*x = AcquireRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquireRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRecord) ProtoMessage() {}

func (x *AcquireRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRecord.ProtoReflect.Descriptor instead.
func (*AcquireRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AckRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AckRecord) Reset() {
	*x = AckRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRecord) ProtoMessage() {}

func (x *AckRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRecord.ProtoReflect.Descriptor instead.
func (*AckRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{4}
}

func (x *AckRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RejectRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RejectRecord) Reset() {
	*x = RejectRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRecord) ProtoMessage() {}

func (x *RejectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRecord.ProtoReflect.Descriptor instead.
func (*RejectRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP(), []int{5}
}

func (x *RejectRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_github_com_dogmatiq_veracity_internal_queue_journal_proto protoreflect.FileDescriptor

var file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDesc = []byte{
	0x0a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67,
	0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x76, 0x65, 0x72, 0x61, 0x63, 0x69, 0x74, 0x79, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x6a, 0x6f,
	0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x65, 0x72,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6f, 0x70, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x73, 0x70, 0x65, 0x63, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x0d, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x39, 0x0a, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x12, 0x39, 0x0a, 0x07, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x36, 0x0a, 0x06, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x65, 0x72,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x22, 0xb2, 0x01, 0x0a, 0x0e,
	0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f,
	0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x64, 0x6f, 0x67, 0x6d, 0x61, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x45, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a,
	0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x4b, 0x0a, 0x0d, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x21, 0x0a,
	0x0d, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x1d, 0x0a, 0x09, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x20, 0x0a, 0x0c, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6f, 0x67, 0x6d, 0x61, 0x74, 0x69, 0x71, 0x2f, 0x76, 0x65, 0x72, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescData = file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDesc
)

func file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescData)
	})
	return file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDescData
}

var file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_dogmatiq_veracity_internal_queue_journal_proto_goTypes = []interface{}{
	(*JournalRecord)(nil),         // 0: veracity.queue.JournalRecord
	(*JournalMessage)(nil),        // 1: veracity.queue.JournalMessage
	(*EnqueueRecord)(nil),         // 2: veracity.queue.EnqueueRecord
	(*AcquireRecord)(nil),         // 3: veracity.queue.AcquireRecord
	(*AckRecord)(nil),             // 4: veracity.queue.AckRecord
	(*RejectRecord)(nil),          // 5: veracity.queue.RejectRecord
	(*envelopespec.Envelope)(nil), // 6: dogma.interop.v1.envelope.Envelope
	(*anypb.Any)(nil),             // 7: google.protobuf.Any
}
var file_github_com_dogmatiq_veracity_internal_queue_journal_proto_depIdxs = []int32{
	2, // 0: veracity.queue.JournalRecord.enqueue:type_name -> veracity.queue.EnqueueRecord
	3, // 1: veracity.queue.JournalRecord.acquire:type_name -> veracity.queue.AcquireRecord
	4, // 2: veracity.queue.JournalRecord.ack:type_name -> veracity.queue.AckRecord
	5, // 3: veracity.queue.JournalRecord.reject:type_name -> veracity.queue.RejectRecord
	6, // 4: veracity.queue.JournalMessage.envelope:type_name -> dogma.interop.v1.envelope.Envelope
	7, // 5: veracity.queue.JournalMessage.meta_data:type_name -> google.protobuf.Any
	1, // 6: veracity.queue.EnqueueRecord.messages:type_name -> veracity.queue.JournalMessage
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_veracity_internal_queue_journal_proto_init() }
func file_github_com_dogmatiq_veracity_internal_queue_journal_proto_init() {
	if File_github_com_dogmatiq_veracity_internal_queue_journal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquireRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*JournalRecord_Enqueue)(nil),
		(*JournalRecord_Acquire)(nil),
		(*JournalRecord_Ack)(nil),
		(*JournalRecord_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_veracity_internal_queue_journal_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_veracity_internal_queue_journal_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_veracity_internal_queue_journal_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_veracity_internal_queue_journal_proto = out.File
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_rawDesc = nil
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_goTypes = nil
	file_github_com_dogmatiq_veracity_internal_queue_journal_proto_depIdxs = nil
}
