// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v4.24.2
// source: github.com/dogmatiq/veracity/internal/eventstream/internal/journalpb/record.proto

package journalpb

// SetAppend sets x.Operation to a [Record_Append] value.
func (x *Record) SetAppend(v *AppendOperation) {
	x.Operation = &Record_Append{Append: v}
}
func (x *Record) DispatchOperation(
	append func(*AppendOperation),
	other func(),
) {
	switch v := x.GetOperation().(type) {
	case *Record_Append:
		append(v.Append)
	default:
		other()
	}
}
