// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v4.24.4
// source: github.com/dogmatiq/veracity/internal/eventstream/internal/journalpb/record.proto

package journalpb

import envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"

// NewRecord returns a new [Record].
func NewRecord() *Record {
	return &Record{}
}

// NewAppendOperation returns a new [AppendOperation].
func NewAppendOperation() *AppendOperation {
	return &AppendOperation{}
}

// Switch_Record_Operation dispatches to one of the given functions based on
// which value of the [Record] message's "Operation" one-of group is populated.
//
// It panics if x.Operation field is nil; otherwise, it returns the value
// returned by the called function. If no return value is required, use a return
// type of [error] and always return nil.
func Switch_Record_Operation[T any](
	x *Record,
	caseAppendOperation func(*AppendOperation) T,
) T {
	switch v := x.Operation.(type) {
	case *Record_AppendOperation:
		return caseAppendOperation(v.AppendOperation)
	default:
		panic("Switch_Record_Operation: x.Operation is nil")
	}
}

// SetStreamOffsetBefore sets the x.StreamOffsetBefore field to v, then returns x.
func (x *Record) SetStreamOffsetBefore(v uint64) *Record {
	if x == nil {
		x = &Record{}
	}
	x.StreamOffsetBefore = v
	return x
}

// SetStreamOffsetAfter sets the x.StreamOffsetAfter field to v, then returns x.
func (x *Record) SetStreamOffsetAfter(v uint64) *Record {
	if x == nil {
		x = &Record{}
	}
	x.StreamOffsetAfter = v
	return x
}

// SetAppendOperation sets the x.Operation field to a [Operation] value containing v, then returns x.
func (x *Record) SetAppendOperation(v *AppendOperation) *Record {
	if x == nil {
		x = &Record{}
	}
	x.Operation = &Record_AppendOperation{AppendOperation: v}
	return x
}

// SetEvents sets the x.Events field to v, then returns x.
func (x *AppendOperation) SetEvents(v []*envelopepb.Envelope) *AppendOperation {
	if x == nil {
		x = &AppendOperation{}
	}
	x.Events = v
	return x
}
